export const cards = [
  {
    _id: 1,
    src: 'https://images.unsplash.com/photo-1613580504360-61c97abb0f5e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
    date: 'November 4, 2020',
    header: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    source: `treehugger`,
    link: '#',
    keyword: 'Nature',
  },
  {
    _id: 2,
    src: 'https://images.unsplash.com/photo-1470770903676-69b98201ea1c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    date: 'February 19, 2019',
    header: 'Nature makes you better',
    text: `We all know how good nature can make us feel. We have known it for millennia: the sound of the ocean, the scents of a forest, the way dappled sunlight dances through leaves.`,
    source: `national geographic`,
    link: '#',
    keyword: 'Nature',
  },
  {
    _id: 3,
    src: 'https://images.unsplash.com/photo-1578583705404-572695c5e32b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1026&q=80',
    date: 'October 19, 2020',
    header: 'Nostalgic Photos of Tourists in U.S. National Parks',
    text: `Uri Løvevild Golman and Helle Løvevild Golman are National Geographic Explorers and conservation photographers who just completed a project and book they call their love letter to...`,
    source: `national geographic`,
    link: '#',
    keyword: 'Yellowstone',
  },
  {
    _id: 4,
    src: 'https://images.unsplash.com/photo-1603781194892-78a8e6f8b77f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    date: 'November 4, 2020',
    header: 'Grand Teton Renews Historic Crest Trail',
    text: `“The linking together of the Cascade and Death Canyon trails, at their heads, took place on October 1, 1933, and marked the first step in the realization of a plan whereby the hiker will be...`,
    source: `National parks traveler`,
    link: '#',
    keyword: 'Parks',
  },
  {
    _id: 5,
    src: 'https://images.unsplash.com/photo-1510981023495-45fca86762e9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80',
    date: 'March 16, 2020',
    header: `Scientists Don't Know Why Polaris Is So Weird`,
    text: `Humans have long relied on the starry sky to push into new frontiers, sail to the very edge of the world and find their way back home again. Even animals look to the stars to guide them. `,
    source: `treehugger`,
    link: '#',
    keyword: 'Photography',
  },
];

export const keywords = ['Nature', 'Yellowstone', 'Parks', 'Photography'];
